In [2]:
import pandas as pd
from IPython.display import display, HTML

In [10]:

df = pd.read_csv("ragbench_evaluation_final.csv", encoding="utf-8")

html = df.head(2).to_html(escape=True)

css = """
<style>
table {
    width: 100%;
    border-collapse: collapse;
}
th, td {
    border: 1px solid #ddd;
    padding: 8px;
    vertical-align: top;
    max-width: 400px;
    white-space: pre-wrap;
    word-break: break-word;
}
</style>
"""

display(HTML(css + html))

In [15]:
print(df['faithfulness'].describe())
print(df['answer_relevancy'].describe())

count    63.000000
mean      0.812562
std       0.223209
min       0.000000
25%       0.666700
50%       0.875000
75%       1.000000
max       1.000000
Name: faithfulness, dtype: float64
count    63.000000
mean      0.693187
std       0.284797
min       0.000000
25%       0.691800
50%       0.762200
75%       0.886100
max       0.952500
Name: answer_relevancy, dtype: float64

In [16]:
print(df['context_precision'].describe())
print(df['context_recall'].describe())

count    62.000000
mean      0.758065
std       0.402268
min       0.000000
25%       0.500000
50%       1.000000
75%       1.000000
max       1.000000
Name: context_precision, dtype: float64
count    63.000000
mean      0.944444
std       0.221998
min       0.000000
25%       1.000000
50%       1.000000
75%       1.000000
max       1.000000
Name: context_recall, dtype: float64

In [8]:

ds = pd.read_json("rag_results_hotpotqa.jsonl", encoding="utf-8", lines=True)

html_ds = ds.head(2).to_html(escape=True)

css = """
<style>
table {
    width: 100%;
    border-collapse: collapse;
}
th, td {
    border: 1px solid #ddd;
    padding: 8px;
    vertical-align: top;
    max-width: 400px;
    white-space: pre-wrap;
    word-break: break-word;
}
</style>
"""

display(HTML(css + html_ds))

In [9]:

dr = pd.read_json("hotpotqa_top500.jsonl", encoding="utf-8", lines=True)

html_dr = dr.head(2).to_html(escape=True)

css = """
<style>
table {
    width: 100%;
    border-collapse: collapse;
}
th, td {
    border: 1px solid #ddd;
    padding: 8px;
    vertical-align: top;
    max-width: 400px;
    white-space: pre-wrap;
    word-break: break-word;
}
</style>
"""

display(HTML(css + html_dr))